// <auto-generated />
namespace MoviesService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changerequired3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changerequired3));
        
        string IMigrationMetadata.Id
        {
            get { return "202201231816482_change-required3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
