// <auto-generated />
namespace MoviesService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changerequired4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changerequired4));
        
        string IMigrationMetadata.Id
        {
            get { return "202201231914240_change-required4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
