// <auto-generated />
namespace MoviesService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changeepisodemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeepisodemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202201081153269_change-episode-model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
